// Datos mock de fallback: permiten demostrar el flujo completo aunque el backend
// todavía no exponga los endpoints. Coordenadas reales alrededor de Formosa capital.
const daysAgo = (d) => new Date(Date.now() - d * 86400000).toISOString();

export const MOCK_PRODUCERS = [
  {
    id: 1,
    name: "Marta Gimenez",
    businessName: "Chacra La Esperanza",
    category: "Frutihortícola",
    phone: "5493704000001",
    email: "marta@laesperanza.ar",
    address: "Colonia Pastoril, Formosa",
    coordinates: { type: "Point", coordinates: [-58.1781, -26.1849] },
    paymentMethods: ["Efectivo", "Transferencia"],
    deliveryOptions: ["Retiro en el local", "Punto de encuentro"],
    bio: "Producción agroecológica familiar desde 1998.",
    createdAt: daysAgo(120),
  },
  {
    id: 2,
    name: "Julio Ayala",
    businessName: "Miel del Monte",
    category: "Apicultura",
    phone: "5493704000002",
    address: "Villa Dos Trece, Formosa",
    coordinates: { type: "Point", coordinates: [-58.2405, -26.1502] },
    paymentMethods: ["Efectivo", "Mercado Pago"],
    deliveryOptions: ["Envío a domicilio"],
    bio: "Miel pura de flora nativa del monte formoseño.",
    createdAt: daysAgo(3),
  },
  {
    id: 3,
    name: "Rosa Benítez",
    businessName: "Tejidos Pilagá",
    category: "Artesanías/Textil",
    phone: "5493704000003",
    address: "Barrio San Antonio, Formosa",
    coordinates: { type: "Point", coordinates: [-58.1601, -26.2032] },
    paymentMethods: ["Efectivo", "Transferencia", "Mercado Pago"],
    deliveryOptions: ["Retiro en el local", "Envío a domicilio"],
    bio: "Telares y bordados de comunidades originarias.",
    createdAt: daysAgo(45),
  },
  {
    id: 4,
    name: "Carlos Duarte",
    businessName: "Dulces Doña Nina",
    category: "Conservas/Dulces",
    phone: "5493704000004",
    address: "El Colorado, Formosa",
    coordinates: { type: "Point", coordinates: [-59.3712, -26.3081] },
    paymentMethods: ["Efectivo"],
    deliveryOptions: ["Punto de encuentro"],
    createdAt: daysAgo(9),
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: "Mandioca fresca",
    producerId: 1,
    category: "Frutihortícola",
    regularPrice: 1200,
    offerPrice: 800,
    isOffer: true,
    stockUnit: "30 kg",
    description: "Excedente de cosecha de esta semana, recién levantada.",
  },
  {
    id: 2,
    title: "Zapallo anco",
    producerId: 1,
    category: "Frutihortícola",
    regularPrice: 900,
    isOffer: false,
    stockUnit: "50 unidades",
  },
  {
    id: 3,
    title: "Miel de espinillo 1kg",
    producerId: 2,
    category: "Apicultura",
    regularPrice: 6500,
    isOffer: false,
    stockUnit: "24 frascos",
    description: "Cosecha de primavera, sin pasteurizar.",
  },
  {
    id: 4,
    title: "Manta de telar",
    producerId: 3,
    category: "Artesanías/Textil",
    regularPrice: 42000,
    offerPrice: 35000,
    isOffer: true,
    stockUnit: "3 unidades",
    description: "Tejida a mano en lana natural teñida con tintes vegetales.",
  },
  {
    id: 5,
    title: "Dulce de mamón",
    producerId: 4,
    category: "Conservas/Dulces",
    regularPrice: 3800,
    isOffer: false,
    stockUnit: "40 frascos",
  },
  {
    id: 6,
    title: "Tomate perita",
    producerId: 1,
    category: "Frutihortícola",
    regularPrice: 2100,
    offerPrice: 1400,
    isOffer: true,
    stockUnit: "18 kg",
    description: "Muy maduro, ideal para salsa. Salida rápida.",
  },
];
